[project]
name = "sprite-game"
version = "0.1"
description = "A simple sprite based hack and slash game"
authors = [
    {name="Stephen Naragon", email="snaragon@my.wctc.edu"}
]
maintainers = [
    {name="Stephen Naragon", email="snaragon@my.wctc.edu"}
]